proStage:
  path: /
  controller: App\Controller\OpenClassDutController::index

entreprises:
  path: /entreprises
  controller: App\Controller\OpenClassDutController::index2

formation:
  path: /formation
  controller: App\Controller\OpenClassDutController::index3

stages:
  path: /stages/{id}
  controller: App\Controller\OpenClassDutController::index4

affichagesRessources:
  path: /affichagesRessources/{nb}
  controller: App\Controller\OpenClassDutController::afficherRessourcesPeda